In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
Matches = pd.read_csv('../input/ipl-data-set/matches.csv')

In [5]:
Matches.head()

The head attribute gives first five rows of given data set

In [6]:
Matches.tail()

The tail attribute gives the last five rows of the given data set

In [7]:
Matches.shape

from this we understood that we have 756 rows and 18 columns

In [8]:
Matches.columns

It gives the columns heading names in the dataset

In [9]:
Matches.dtypes.value_counts()

We have 14 categorical values and '4' integer columns and the return datatype is integer

In [12]:
missing = Matches.isnull()

In [13]:
missing

In [14]:
Matches.isnull().sum()

Here there are Null Values we want to remove null values first

In [16]:
plt.figure(figsize=(15,7))
sns.countplot(x='Season', data=Matches , order=Matches['Season'].value_counts().index.sort_values())
plt.xlabel('Season',fontsize=12)
plt.ylabel('No of matches played in each ipl season', fontsize=12)
plt.tittle('Number of matches played in each IPL season', fontsize=16)

Here it tells the no.of matches played by all teams in IPL session from 2008 to 2019
In 2013 no.of matches will be highest  and in 2009 the no.of Ipl matches will be least

In [17]:
Matches['win_by_runs'].describe()

It is used to view some basic Statistical Details like mean,mode,median etc..,

In [19]:
sns.set(rc={'figure.figsize' : (12,8)})
sns.displot(Matches['win_by_runs'], kde=False, bins=20);

It tells about the matches wins by how many runs in each IPL session from 2008 to 2019

In [20]:
sns.kdeplot(Matches['win_by_runs'])

It tells about the no.of matches in each IPL session from 2008 to 2019

CONCLUSION:
   This dataset tells about the winners of the match who won by how many runs in the IPL session from 2008 to 2019
   This tells about the venue of the match and also the winners who won the match
   Its tells about the match detaila of the particular day and who won by wickets